/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package domain;

import java.util.Scanner;
import java.sql.*;
import java.util.HashSet;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Logger;
import javax.security.auth.callback.ConfirmationCallback;

/**
 *
 * @author admin
 */
public class form extends javax.swing.JFrame {

    int curenRecord, totalRecord;
    Vector tbl = new Vector();
    Vector tblTitle = new Vector();
    dbconnection dbcon = new dbconnection();
    Connection cnn;

    public form() {
        initComponents();
        tblTitle.add("Ma giang vien ");
        tblTitle.add("Ten hiang vien ");
        tblTitle.add("Dia chi");
        tblTitle.add("He so luong ");
        Hienthibanghi();
        Hienthibang();

    }

    public void Hienthibanghi() {
        curenRecord = tbgv.getSelectedRow();
        totalRecord = tbgv.getRowCount();
        lblso.setText((curenRecord + 1) + "/" + totalRecord);

    }

    public void Hienthidulieulenform(int row) {
        Vector r = (Vector) tbl.get(row);
        txtmagv.setText(r.get(0).toString());
        txttengv.setText(r.get(1).toString());
        txtdiachi.setText(r.get(2).toString());
        txthesoluong.setText(r.get(3).toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblqlgv = new javax.swing.JLabel();
        jpan = new javax.swing.JPanel();
        lblmagv = new javax.swing.JLabel();
        lbltengv = new javax.swing.JLabel();
        lbldiachi = new javax.swing.JLabel();
        lblhesoluong = new javax.swing.JLabel();
        txtmagv = new javax.swing.JTextField();
        txttengv = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txthesoluong = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbgv = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnxoa = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();
        btndau = new javax.swing.JButton();
        btntruoc = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btntimkiem = new javax.swing.JButton();
        Thoat = new javax.swing.JButton();
        lblso = new javax.swing.JLabel();
        btnsau = new javax.swing.JButton();
        btncuoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblqlgv.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblqlgv.setText("Quan li giang vien");

        lblmagv.setText("Ma giang vien");

        lbltengv.setText("Ten giang vien");

        lbldiachi.setText("Dia chi");

        lblhesoluong.setText("He so luong");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanLayout = new javax.swing.GroupLayout(jpan);
        jpan.setLayout(jpanLayout);
        jpanLayout.setHorizontalGroup(
            jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmagv)
                    .addComponent(lbltengv)
                    .addComponent(lbldiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhesoluong))
                .addGap(32, 32, 32)
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtmagv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(txttengv, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txthesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jpanLayout.setVerticalGroup(
            jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmagv)
                    .addComponent(txtmagv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltengv)
                    .addComponent(txttengv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldiachi)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhesoluong)
                    .addComponent(txthesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbgv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ma giang vien", "Ten giang vien", "Dia chi", "He so luong"
            }
        ));
        tbgv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbgvMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbgv);

        btnxoa.setText("Xoa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnhuy.setText("Huy");

        btndau.setText("Dau");
        btndau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndauActionPerformed(evt);
            }
        });

        btntruoc.setText("Truoc");
        btntruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntruocActionPerformed(evt);
            }
        });

        btnthem.setText("Them");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sua");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btntimkiem.setText("tim kiem");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        Thoat.setText("Thoat");
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });

        lblso.setForeground(new java.awt.Color(153, 0, 153));
        lblso.setText("1/10");
        lblso.setToolTipText("");

        btnsau.setText("sau");
        btnsau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsauActionPerformed(evt);
            }
        });

        btncuoi.setText("Cuoi");
        btncuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addGap(89, 89, 89))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btntimkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsua)
                    .addComponent(Thoat))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnhuy)
                    .addComponent(btnxoa))
                .addGap(88, 88, 88))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btndau)
                .addGap(18, 18, 18)
                .addComponent(btntruoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblso)
                .addGap(28, 28, 28)
                .addComponent(btnsau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncuoi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnthem)
                            .addComponent(btnsua)
                            .addComponent(btnxoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btntimkiem)
                            .addComponent(Thoat)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnhuy)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndau)
                    .addComponent(btntruoc)
                    .addComponent(lblso)
                    .addComponent(btnsau)
                    .addComponent(btncuoi)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lblqlgv))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpan, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblqlgv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        String magv = txtmagv.getText().toString();
        String tengv = txttengv.getText().toString();
        String diachi = txtdiachi.getText().toString();
        int hesoluong = Integer.parseInt(txthesoluong.getText().toString());
        try {
            cnn = dbcon.open();
            if (cnn != null) {
                String sqlcmd = "Insert into giangvien values('" + magv + "','" + tengv + "','" + diachi + "','" + hesoluong + "')";
                PreparedStatement ps = cnn.prepareStatement(sqlcmd);
                ps.execute();
                JOptionPane.showMessageDialog(null, "da them thanh cong ");
                Hienthibang();
                cnn.close();

            } else {
                JOptionPane.showMessageDialog(null, "loi ket noi csdl");
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        String magv = txtmagv.getText();
        String tengv = txttengv.getText();
        String diachi = txtdiachi.getText();
        int hesoluong = Integer.parseInt(txthesoluong.getText());
        try {
            cnn = dbcon.open();
            if (cnn != null) {
                String sqlcmd = "UPDATE giangvien SET tengv= '"
                        + tengv + "',diachi= '"
                        + diachi + "',hesoluong= '"
                        + hesoluong + "'WHERE magv= '" + magv + "'";
                PreparedStatement ps = cnn.prepareStatement(sqlcmd);
                ps.execute();
                JOptionPane.showMessageDialog(null, "cap nnhat thamnh cong ");
                cnn.close();
                Hienthibang();

            } else {
                JOptionPane.showMessageDialog(null, "loi ket noi co so du lieu");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        String magv=txtmagv.getText();
        try {
            cnn=dbcon.open();
            if (cnn!=null) {
                String sqlcmd="Delete from giangvien WHERE magv= '"+magv+"'";
                PreparedStatement ps= cnn.prepareStatement(sqlcmd);
                int result=JOptionPane.showConfirmDialog(null, "ban co muon xoa bang khong?","xac nhan",JOptionPane.YES_NO_OPTION);
                 if(result==0){
                     ps.execute();
                     Hienthibang();
                 }       
                        
                        
                        
                
                
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnxoaActionPerformed

    private void tbgvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbgvMouseClicked
        // TODO add your handling code here:
        int r = tbgv.getSelectedRow();
        Vector rdata = (Vector) tbl.get(r);
        txtmagv.setText(rdata.get(0).toString());
        txttengv.setText(rdata.get(1).toString());
        txtdiachi.setText(rdata.get(2).toString());
        txthesoluong.setText(rdata.get(3).toString());

        Hienthibanghi();
        
    }//GEN-LAST:event_tbgvMouseClicked

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
            this,
            "Bạn có muốn thoát không?",
            "Xác nhận thoát",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

    // Check the user's response
    if (response == JOptionPane.YES_OPTION) {
        // Exit the application
        System.exit(0);
    }
    }//GEN-LAST:event_ThoatActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
         tbl.removeAll(tbl);
        try {
            cnn = dbcon.open();
            if (cnn != null) {
                String sqlcmd = "Select*from giangvien where magv="+txtmagv.getText()+"";
                PreparedStatement ps = cnn.prepareStatement(sqlcmd);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    Vector row = new Vector();
                    row.add(rs.getString("magv"));
                    row.add(rs.getString("tengv"));
                    row.add(rs.getString("diachi"));
                    row.add(rs.getInt("hesoluong"));
                    tbl.add(row);

                }
                tbgv.setModel(new DefaultTableModel(tbl, tblTitle));
                cnn.close();
            } else {
                JOptionPane.showMessageDialog(null, "loi ket noi csdl");

            }
        } catch (SQLException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void btndauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndauActionPerformed
        // TODO add your handling code here:
         curenRecord = 0;
        tbgv.getSelectionModel().setSelectionInterval(curenRecord, curenRecord);
        Hienthibanghi();
        Hienthidulieulenform(curenRecord);
    }//GEN-LAST:event_btndauActionPerformed

    private void btntruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntruocActionPerformed
        // TODO add your handling code here:
         if(curenRecord > 0){
             curenRecord--;
             tbgv.getSelectionModel().setSelectionInterval(curenRecord, curenRecord);
        Hienthibanghi();
        Hienthidulieulenform(curenRecord);
         }
        
    }//GEN-LAST:event_btntruocActionPerformed

    private void btnsauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsauActionPerformed
        // TODO add your handling code here:
         if (curenRecord < totalRecord - 1) {
            curenRecord++;
            tbgv.getSelectionModel().setSelectionInterval(curenRecord, curenRecord);
            Hienthibanghi();
            Hienthidulieulenform(curenRecord);
        }
    }//GEN-LAST:event_btnsauActionPerformed

    private void btncuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuoiActionPerformed
        // TODO add your handling code here:
         curenRecord = totalRecord-1;
        tbgv.getSelectionModel().setSelectionInterval(curenRecord, curenRecord);
        Hienthibanghi();
        Hienthidulieulenform(curenRecord);
        
    }//GEN-LAST:event_btncuoiActionPerformed
    public void Hienthibang() {
        tbl.removeAll(tbl);
        try {
            cnn = dbcon.open();
            if (cnn != null) {
                String sqlcmd = "Select*from giangvien";
                PreparedStatement ps = cnn.prepareStatement(sqlcmd);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    Vector row = new Vector();
                    row.add(rs.getString("magv"));
                    row.add(rs.getString("tengv"));
                    row.add(rs.getString("diachi"));
                    row.add(rs.getFloat("hesoluong"));
                    tbl.add(row);

                }
                tbgv.setModel(new DefaultTableModel(tbl, tblTitle));
                cnn.close();
            } else {
                JOptionPane.showMessageDialog(null, "loi ket noi csdl");

            }
        } catch (SQLException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Thoat;
    private javax.swing.JButton btncuoi;
    private javax.swing.JButton btndau;
    private javax.swing.JButton btnhuy;
    private javax.swing.JButton btnsau;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btntruoc;
    private javax.swing.JButton btnxoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpan;
    private javax.swing.JLabel lbldiachi;
    private javax.swing.JLabel lblhesoluong;
    private javax.swing.JLabel lblmagv;
    private javax.swing.JLabel lblqlgv;
    private javax.swing.JLabel lblso;
    private javax.swing.JLabel lbltengv;
    private javax.swing.JTable tbgv;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txthesoluong;
    private javax.swing.JTextField txtmagv;
    private javax.swing.JTextField txttengv;
    // End of variables declaration//GEN-END:variables
}
